# Generated by Django 5.1.1 on 2024-11-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcos',
            options={'verbose_name': 'Marco', 'verbose_name_plural': 'Marcos'},
        ),
    ]
