# Generated by Django 5.1.1 on 2024-09-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trabajadores',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido_P', models.CharField(max_length=100)),
                ('Apellido_M', models.CharField(max_length=100)),
                ('Fecha_N', models.DateField()),
                ('cod_rol', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
