# Generated by Django 5.1.1 on 2024-10-07 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

def create_roles(apps, schema_editor):
    Rol = apps.get_model('gestion_usuarios', 'Rol') 
    Rol.objects.create(nombre='Administrador', descripcion='Tiene control total del sistema')
    Rol.objects.create(nombre='Trabajador', descripcion='Acceso limitado para realizar tareas asignadas')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_p', models.CharField(max_length=100)),
                ('apellido_m', models.CharField(max_length=100)),
                ('fecha_n', models.DateField()),
                ('correo', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('codigo_recuperacion', models.CharField(blank=True, max_length=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuarios_groups', to='auth.group')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.rol')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarios_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=20)),
                ('estado', models.CharField(choices=[('en_espera', 'En Espera'), ('en_progreso', 'En Progreso'), ('terminada', 'Terminada')], default='en_espera', max_length=20)),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='reportes_problemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidente', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('marco', models.CharField(blank=True, max_length=255, null=True)),
                ('medida_marco', models.TextField(default='Sin medir')),
                ('foto_url', models.ImageField(blank=True, null=True, upload_to='reportes_fotos/')),
                ('fecha_reporte', models.DateTimeField(default='2024-06-01')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_De_Cambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Asignaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('En espera', 'En espera'), ('En progreso', 'En progreso'), ('Completada', 'Completada')], default='En espera', max_length=20)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.tareas')),
                ('trabajador', models.ForeignKey(limit_choices_to={'rol__nombre': 'Trabajador'}, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuarios')),
            ],
        ),
    ]
