# Generated by Django 5.1.1 on 2024-10-13 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='fecha_asignacion',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='rut_usuario',
        ),
        migrations.AlterField(
            model_name='reportes_problemas',
            name='fecha_reporte',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('En espera', 'En espera'), ('En progreso', 'En progreso'), ('Completada', 'Completada')], default='En espera', max_length=20)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.tareas')),
                ('trabajador', models.ForeignKey(limit_choices_to={'rol__nombre': 'Trabajador'}, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Gestion_Fallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('ubicacion_geografica', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_reporte', models.DateTimeField()),
                ('id_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.reportes_problemas')),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuarios')),
            ],
        ),
        migrations.DeleteModel(
            name='Asignaciones',
        ),
    ]
