# Generated by Django 5.1.1 on 2024-09-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_alter_trabajadores_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='Apellido_M',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='Apellido_P',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='Nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='cod_rol',
            field=models.IntegerField(verbose_name=1),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='id_trabajador',
            field=models.AutoField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
