# Generated by Django 5.1.1 on 2024-09-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0004_trabajadores_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reportes_Problemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidente', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('marco', models.CharField(blank=True, max_length=255, null=True)),
                ('medida_marco', models.TextField(default='Sin medir')),
                ('foto_url', models.ImageField(blank=True, null=True, upload_to='reportes_fotos/')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.trabajadores')),
            ],
        ),
        migrations.CreateModel(
            name='Gestion_Fallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('ubicacion_geografica', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_reporte', models.DateTimeField()),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.trabajadores')),
                ('id_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.reportes_problemas')),
            ],
        ),
    ]
