# Generated by Django 5.1.1 on 2024-09-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0005_rol_reportes_problemas_gestion_fallas'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion_fallas',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestion_fallas',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
