# Generated by Django 5.1.1 on 2024-09-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0006_gestion_fallas_latitud_gestion_fallas_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes_problemas',
            name='fecha_reporte',
            field=models.DateTimeField(null=True),
        ),
    ]
