# Generated by Django 5.1.1 on 2024-09-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0007_alter_reportes_problemas_fecha_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes_problemas',
            name='fecha_reporte',
            field=models.DateField(null=True),
        ),
    ]
