# Generated by Django 5.1.1 on 2024-10-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problemas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
    ]
