# Generated by Django 5.1.1 on 2024-10-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_datos', '0002_problemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marco', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
    ]
