# Generated by Django 5.1.1 on 2024-10-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_datos', '0003_marcos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcos',
            old_name='marco',
            new_name='nombre',
        ),
    ]
