# Generated by Django 5.1.1 on 2024-11-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reportes', '0002_reportes_problemas_es_predeterminado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportes_problemas',
            name='es_predeterminado',
        ),
        migrations.AddField(
            model_name='tareas',
            name='es_predeterminado',
            field=models.BooleanField(default=False),
        ),
    ]
