# Generated by Django 5.1.1 on 2024-11-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes_problemas',
            name='es_predeterminado',
            field=models.BooleanField(default=False),
        ),
    ]
